In [16]:
import pandas as pd
df= pd.read_csv("student_data_apply_map_pipe.csv")
df.head()

df["Department"] = df["Department"].map({
    "CS": "Computer Science",
    "SE": "Software Engineering",
    "IT": "Information Technology"
})

df.head()

     Name              Department  Marks  Attendance Fee_Status
0     Ali        Computer Science     78          90       Paid
1   Ahmed    Software Engineering     65          75     Unpaid
2    Sara  Information Technology     92          98       Paid
3   Usman    Software Engineering     55          62     Unpaid
4  Ayesha        Computer Science     88          94       Paid

In [20]:
import pandas as pd
df= pd.read_csv("student_data_apply_map_pipe.csv")
df.head()
df["Department"] = df["Department"].map({
    "CS": "Computer Science",
    "SE": "Software Engineering",
    "IT": "Information Technology"
})

df.head()

     Name              Department  Marks  Attendance Fee_Status
0     Ali        Computer Science     78          90       Paid
1   Ahmed    Software Engineering     65          75     Unpaid
2    Sara  Information Technology     92          98       Paid
3   Usman    Software Engineering     55          62     Unpaid
4  Ayesha        Computer Science     88          94       Paid

In [25]:
df= pd.read_csv("student_data_apply_map_pipe.csv")
df.head()
df["Fee_Status"]= df["Fee_Status"].map({
    "Paid": "FEE SUBMITTED",
    "Unpaid" : "FEE SUBMITTING"
})

df[["Name" , "Fee_Status"]].head()

     Name      Fee_Status
0     Ali   FEE SUBMITTED
1   Ahmed  FEE SUBMITTING
2    Sara   FEE SUBMITTED
3   Usman  FEE SUBMITTING
4  Ayesha   FEE SUBMITTED

In [26]:
def double_marks(data):
    return data * 2

df["Double_Marks"] = df["Marks"].pipe(double_marks)

df[["Name", "Marks", "Double_Marks"]].head()

     Name  Marks  Double_Marks
0     Ali     78           156
1   Ahmed     65           130
2    Sara     92           184
3   Usman     55           110
4  Ayesha     88           176

In [27]:
def double_marks(data):
    return data * 2

df["Double_Marks"] = df["Marks"].pipe(double_marks)

df[["Name", "Marks", "Double_Marks"]].head()

     Name  Marks  Double_Marks
0     Ali     78           156
1   Ahmed     65           130
2    Sara     92           184
3   Usman     55           110
4  Ayesha     88           176

In [28]:
df.describe

<bound method NDFrame.describe of      Name Department  Marks  Attendance      Fee_Status  Double_Marks
0     Ali         CS     78          90   FEE SUBMITTED           156
1   Ahmed         SE     65          75  FEE SUBMITTING           130
2    Sara         IT     92          98   FEE SUBMITTED           184
3   Usman         SE     55          62  FEE SUBMITTING           110
4  Ayesha         CS     88          94   FEE SUBMITTED           176
5   Bilal         IT     73          80   FEE SUBMITTED           146
6    Hina         SE     81          89  FEE SUBMITTING           162
7   Hamza         CS     60          68   FEE SUBMITTED           120
8  Fatima         IT     95          99   FEE SUBMITTED           190
9    Zain         SE     69          77  FEE SUBMITTING           138>