In [8]:
%pip install pandas as pd

Requirement already satisfied: pandas in c:\users\zia ullah\anaconda3\lib\site-packages (2.3.3)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as

In [40]:
Customer = pd.DataFrame({
    "customer_id":[1,2,3],
    "Name":["Alice","Bob","Charlie"]
})

In [41]:
orders = pd.DataFrame({
    "orders_id":[101,102,103,104],
    "customer_id":[1,2,2,3],
    "Amount": [100,120,150,200]
    
})

In [42]:

df_inner= pd.merge(Customer , orders, on="customer_id", how="inner")
print(df_inner)

   customer_id     Name  orders_id  Amount
0            1    Alice        101     100
1            2      Bob        102     120
2            2      Bob        103     150
3            3  Charlie        104     200

In [43]:
df_left=pd.merge(Customer , orders, on="customer_id", how="left")
df_left

   customer_id     Name  orders_id  Amount
0            1    Alice        101     100
1            2      Bob        102     120
2            2      Bob        103     150
3            3  Charlie        104     200

In [44]:
df_outer=pd.merge(Customer , orders, on="customer_id", how="outer")
df_outer

   customer_id     Name  orders_id  Amount
0            1    Alice        101     100
1            2      Bob        102     120
2            2      Bob        103     150
3            3  Charlie        104     200