In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\zia ullah\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\zia ullah\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\zia ullah\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\zia ullah\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\zia ullah\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\zia ullah\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd

In [7]:
s= pd.Series([10,20,30,40,20],index=["a","b", "c","d","e"])
s

a    10
b    20
c    30
d    40
e    20
dtype: int64

In [10]:
print(s.values)
print(s.index)
print(s.dtype)

[10 20 30 40 20]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
int64

In [11]:
print(s.head)

<bound method NDFrame.head of a    10
b    20
c    30
d    40
e    20
dtype: int64>

In [12]:
print(s.tail)

<bound method NDFrame.tail of a    10
b    20
c    30
d    40
e    20
dtype: int64>

In [14]:
print(s.value_counts())

20    2
10    1
30    1
40    1
Name: count, dtype: int64

dataframe

In [18]:
data= {
    "Name" : ["Ali", "Rehman", "raza"],
    "Ages" : [10,20,16],
    "City": ["skardu", "bahawalpur","Lahore"]
}

df = pd.DataFrame(data)
print(df)

     Name  Ages        City
0     Ali    10      skardu
1  Rehman    20  bahawalpur
2    raza    16      Lahore

In [21]:
#load csv file
df =pd.read_csv("customers-100.csv")
print("information\n", df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB
information
 None

In [24]:
print(df.shape)

(100, 12)

In [25]:
print("STATISTICAL INFO \n" , df.describe)

STATISTICAL INFO
 <bound method NDFrame.describe of     Index Customer Id First Name Last Name                     Company  \
0       1  KHID4HiDzp     Hector     Huang                Baxter Group
1       2  W50PcDdk1a     Marcus      Hahn                 Rich-Santos
2       3  acQ3W8B4t8     Cassie     Walsh                  Shea-Ewing
3       4  4QMeOJZ0vf      Erica    Powers   Petersen, Sloan and Boyer
4       5  GXdMtnn172       Carl    Kelley  Hale, Williamson and Bates
..    ...         ...        ...       ...                         ...
95     96  SV50Zl6Yrt     Lonnie   Simmons     Coleman, Shea and Solis
96     97  HVSGs43yc1    Raymond    Decker                   Yoder Ltd
97     98  vHpSg22tjc       Rick    Dillon              Mercer-Flowers
98     99  TZOMKyTZgW      Tammy   Padilla                 Robbins PLC
99    100  Tlgu4ySmkG       Earl  Guerrero    Conrad, Hartman and Mann

             City                       Country              Phone 1  \
0   Port Ianshire                       Finland           6233837777
1      West Erica                   New Zealand     250-574-1941x405
2      New Joanne                Cayman Islands     001-568-835-1828
3    Patriciaberg  Svalbard & Jan Mayen Islands         483.525.2396
4     New Danberg           Trinidad and Tobago        (313)729-8953
..            ...                           ...                  ...
95     North Kara                     Australia      +1-935-980-3224
96       Tommouth                  Saint Martin        (844)596-3986
97      West Dale                      Paraguay    628-542-9143x3484
98  Dodsonborough                      Maldives  (232)805-1256x78944
99   Hamptonshire                         Congo           3417177923

                 Phone 2                              Email Subscription Date  \
0      (302)564-9011x928  janecooper@chambers-underwood.com        2022-06-12
1    +1-810-810-1744x956       mercedes43@hooper-newman.com        2020-12-06
2      603-949-6270x4521           eddiedelacruz@malone.com        2022-09-25
3   001-639-783-4487x497           waynepeters@melendez.com        2020-06-05
4           928.736.3321         derek18@douglas-travis.org        2026-04-23
..                   ...                                ...               ...
95  +1-882-969-1339x9768                 sherry26@cross.net        2024-02-16
96         (269)242-4510           madisonmurillo@leach.com        2025-04-07
97     285-991-1643x1682             gravesnoah@hampton.com        2024-12-28
98         (220)979-9910       carlosgreer@orozco-david.org        2021-07-15
99         (465)919-5684              alecwells@sampson.net        2021-07-22

                              Website
0                  http://gamble.org/
1                     http://key.com/
2                  https://woods.com/
3   https://www.carlson-cantrell.com/
4                   http://tapia.com/
..                                ...
95              http://www.brady.com/
96           http://www.fletcher.com/
97         http://www.villanueva.com/
98                https://bailey.com/
99                https://graham.com/

[100 rows x 12 columns]>

pandas indexinf and selection

In [40]:
data= {
    "Name" : ["Ali", "Rehman", "raza", "Farhan"],
    "Ages" : [10,20,16,17],
    "class":[1,2,3,4],
    "City": ["skardu", "bahawalpur","Lahore","karachi"],

}

df = pd.DataFrame(data)
print(df)

     Name  Ages  class        City
0     Ali    10      1      skardu
1  Rehman    20      2  bahawalpur
2    raza    16      3      Lahore
3  Farhan    17      4     karachi

In [42]:
subset_loc = df.loc[1:3, ["Name", "City"]]
print(subset_loc)

     Name        City
1  Rehman  bahawalpur
2    raza      Lahore
3  Farhan     karachi

In [46]:
subset_iloc= df.iloc[1:3 , 1:3]
print(subset_iloc)

   Ages  class
1    20      2
2    16      3

In [47]:
high_salary= df[df["Ages"]> 15]
print(high_salary)

     Name  Ages  class        City
1  Rehman    20      2  bahawalpur
2    raza    16      3      Lahore
3  Farhan    17      4     karachi

In [50]:
df.loc[df["Ages"] <20, "'class"]= 6
print(df.loc[df["Ages"] <20, "'class"])

0    6.0
2    6.0
3    6.0
Name: 'class, dtype: float64

In [51]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\zia ullah\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\zia ullah\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [61]:
df= pd.read_csv("customers-100.csv",
                parse_dates=["City"],
                dtype={
                    "Category": "category",
                    "Region": "category"
                }
                )
df.info()

C:\Users\Zia Ullah\AppData\Local\Temp\ipykernel_3808\1306853727.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df= pd.read_csv("customers-100.csv",

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

In [66]:
df.to_excel("customers.xlsx")

In [65]:
df.to_json("customer.json")

In [70]:
df = pd.read_csv("retail_sales_dataset.csv",
                 parse_dates=["Date"],
                 dtype={
                     "Category": "category"
                 }
                 )
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[ns]
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: datetime64[ns](1), int64(5), object(3)
memory usage: 70.4+ KB

In [80]:
df= pd.read_csv("retail_sales_dataset.csv",
                parse_dates=["Date"],
                dtype={
                    "Category": "category",
                    "Region": "category"
                }
                )
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[ns]
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   object
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      995 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(3), object(4)
memory usage: 70.4+ KB

In [81]:
print(df.isna().sum())

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        5
dtype: int64

In [82]:
df = pd.read_csv("practice.csv")
print(df)

    Name   Age  Marks    City
0    Ali  20.0   80.0  Lahore
1  Ahmed   NaN   70.0  Multan
2   Sara  22.0    NaN  Lahore
3  Usman  24.0   90.0     NaN
4   Zain  20.0   70.0  Multan

In [84]:
print(df.isna().sum())

Name     0
Age      1
Marks    1
City     1
dtype: int64

In [86]:
#fill with mean
df["Age"]= df["Age"].fillna(df["Age"].mean())

In [87]:
df["Marks"]= df["Marks"].fillna(df["Marks"].median())

In [97]:
df["City"]= df["City"].fillna(df["City"].mode())

In [99]:
print(df)

    Name   Age  Marks    City
0    Ali  20.0   80.0  Lahore
1  Ahmed  21.5   70.0  Multan
2   Sara  22.0   75.0  Lahore
3  Usman  24.0   90.0  Lahore
4   Zain  20.0   70.0  Multan

In [100]:
df.isna()

    Name    Age  Marks   City
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False

In [101]:
df=pd.DataFrame({
    "Category": ["Electronics", "furnitue", "Home-Appliance", " electronic", "FURNITURE"]
})

In [102]:
print(df)

         Category
0     Electronics
1        furnitue
2  Home-Appliance
3      electronic
4       FURNITURE

In [115]:
df["Ccategory_clean"]= df['Category'].str.strip().str.lower()

In [104]:
print(df)

         Category  Category_clean
0     Electronics     electronics
1        furnitue        furnitue
2  Home-Appliance  home-appliance
3      electronic      electronic
4       FURNITURE       furniture

In [117]:
df["Category_clean"]= df["Category"].str.replace("-", " ")
df

         Category  Category_clean  category_clean Ccategory_clean
0     Electronics     Electronics     Electronics     electronics
1        furnitue        furnitue        furnitue        furnitue
2  Home-Appliance  Home Appliance  Home Appliance  home-appliance
3      electronic      electronic      electronic      electronic
4       FURNITURE       FURNITURE       FURNITURE       furniture

In [124]:
df=pd.read_csv("practice.csv")
print(df)
sorted_value= df.sort_values(by="Age", ascending=True)
print("Sorted Values")
print(sorted_value)

    Name   Age  Marks    City
0    Ali  20.0   80.0  Lahore
1  Ahmed   NaN   70.0  Multan
2   Sara  22.0    NaN  Lahore
3  Usman  24.0   90.0     NaN
4   Zain  20.0   70.0  Multan
Sorted Values
    Name   Age  Marks    City
0    Ali  20.0   80.0  Lahore
4   Zain  20.0   70.0  Multan
2   Sara  22.0    NaN  Lahore
3  Usman  24.0   90.0     NaN
1  Ahmed   NaN   70.0  Multan

In [126]:
sorted_value= df.sort_values(by="Age", ascending=False)
sorted_value

    Name   Age  Marks    City
3  Usman  24.0   90.0     NaN
2   Sara  22.0    NaN  Lahore
0    Ali  20.0   80.0  Lahore
4   Zain  20.0   70.0  Multan
1  Ahmed   NaN   70.0  Multan

In [140]:
df = pd.read_csv("practice.csv")

df["Rank"]=df["Age"].rank(
    ascending=False,
    method="min")

print(df.sort_values(by="Rank"))

    Name   Age  Marks    City  Rank
3  Usman  24.0   90.0     NaN   1.0
2   Sara  22.0    NaN  Lahore   2.0
0    Ali  20.0   80.0  Lahore   3.0
4   Zain  20.0   70.0  Multan   3.0
1  Ahmed   NaN   70.0  Multan   NaN

In [136]:


df = pd.read_csv("practice.csv")

df["Rank"] = df["Marks"].rank(
    ascending=False,
    method="min"
)

print(df.sort_values(by="Rank"))

    Name   Age  Marks    City  Rank
3  Usman  24.0   90.0     NaN   1.0
0    Ali  20.0   80.0  Lahore   2.0
1  Ahmed   NaN   70.0  Multan   3.0
4   Zain  20.0   70.0  Multan   3.0
2   Sara  22.0    NaN  Lahore   NaN